### ISSUE TITLE
Exception getting bars...

### ISSUE THREAD

**Issue by robertZaufall** [jbpayton/langchain-stock-screener#1]
Great project! Unfortunately I cannot get it to work.

First an "end" parameter was needed getting the bars.
When I provide one (eg. end=self.lastDate) I'm getting another exception:  'str' object has no attribute 'value'.

**Comment by claycampbell** [comment]
Try this fixed fetch_symbol
def fetch_symbol(self, api, barTime, symbol):
        while True:  # Add this loop
            try:
                # Define the start and end timestamps in ISO format
                start_date_iso = self.lastDate + "T00:00:00-04:00"
                end_date_iso = datetime.datetime.now().isoformat() + "-04:00"
                
                # Fetch the bars using the Alpaca API
                returned_data = api.get_bars(symbol, barTime, start=start_date_iso, end=end_date_iso)
                break  # If get_bars succeeds, break the loop
            except Exception as e:  
                print(f"Exception: {e}")
                print("Retrying in 5 seconds...")
                time.sleep(5)

        if returned_data.df.empty:
            return None, None, None, None, None, None

**Comment by robertZaufall** [comment]
thanks! this helped me 😊
